# This is an example configuration that loads the "Kitchen" scene from the
# local MoveIt warehouse and benchmarks the "panda_arm" group in the Pick1
# query using the Start1 initial state (all pre-stored in the local warehouse)

# Three different planners from OMPL are run a total of 50 times each, with a
# maximum of 10 seconds per run.  Output is stored in the /tmp/moveit_benchmarks directory.
warehouse:
    host: localhost
    port: 33829
    scene_name: PickUp     # Required
parameters:
    name: PickingUpItem
    runs: 1
    group: arm       # Required
    timeout: 10.0
    output_directory: /tmp/moveit_benchmarks/
    queries: above
    start_states: rbkairos_state_0000_above
planning_pipelines:
    pipelines: [pipeline1]
    pipeline1:
        name: ompl
        planners:
            - LazyPRMstarkConfigDefault
            - TRRTkConfigDefault
            - RRTConnectkConfigDefault
            # - APSConfigDefault
            # - SBLkConfigDefault
            # - ESTkConfigDefault
            # - LBKPIECEkConfigDefault
            # - BKPIECEkConfigDefault
            # - KPIECEkConfigDefault
            # - RRTkConfigDefault
            # - RRTstarkConfigDefault
            # - PRMkConfigDefault
            # - PRMstarkConfigDefault
            # - FMTkConfigDefault
            # - BFMTkConfigDefault
            # - PDSTkConfigDefault
            # - STRIDEkConfigDefault
            # - BiTRRTkConfigDefault
            # - LBTRRTkConfigDefault
            # - BiESTkConfigDefault
            # - ProjESTkConfigDefault
            # - LazyPRMkConfigDefault
            # - SPARSkConfigDefault
            # - SPARStwokConfigDefault
            # - TrajOptDefault
        # name: chomp
        # planners:
        #     - CHOMP